{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-collector
  labels:
    app.kubernetes.io/name: collector
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: collector
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: collector
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: collector
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: COLLECTOR_MQ_ADDR
              value: "{{ .Release.Name }}-mq:50051"
            - name: VANTAGE_DB_DSN
              value: "postgres://vantage:vantage@{{ .Release.Name }}-postgresql:5432/vantage?sslmode=disable"
{{- end }}
