// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: mq.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TelemetryMessage carries a single DCGM GPU metric reading.
// Fields map to DCGM CSV columns: timestamp, metric_name, gpu_id, device,
// uuid, modelName (→ model_name), Hostname (→ hostname), container, pod,
// namespace, value, labels_raw.
//
// WARNING: Field numbers are stable once deployed. Never renumber fields.
// Adding new fields is backwards compatible; removing or renumbering is not.
type TelemetryMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                     // ISO 8601 UTC; restamped by Streamer with time.Now().UTC().Format(time.RFC3339)
	MetricName    string                 `protobuf:"bytes,2,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"` // e.g., "DCGM_FI_DEV_GPU_UTIL"
	GpuId         string                 `protobuf:"bytes,3,opt,name=gpu_id,json=gpuId,proto3" json:"gpu_id,omitempty"`                // e.g., "0"
	Device        string                 `protobuf:"bytes,4,opt,name=device,proto3" json:"device,omitempty"`                           // e.g., "nvidia0"
	Uuid          string                 `protobuf:"bytes,5,opt,name=uuid,proto3" json:"uuid,omitempty"`                               // GPU UUID
	ModelName     string                 `protobuf:"bytes,6,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`    // e.g., "NVIDIA H100 80GB HBM3"
	Hostname      string                 `protobuf:"bytes,7,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Container     string                 `protobuf:"bytes,8,opt,name=container,proto3" json:"container,omitempty"`
	Pod           string                 `protobuf:"bytes,9,opt,name=pod,proto3" json:"pod,omitempty"`
	Namespace     string                 `protobuf:"bytes,10,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Value         float64                `protobuf:"fixed64,11,opt,name=value,proto3" json:"value,omitempty"`                        // metric value (GPU utilization %, memory bytes, etc.)
	LabelsRaw     string                 `protobuf:"bytes,12,opt,name=labels_raw,json=labelsRaw,proto3" json:"labels_raw,omitempty"` // raw Prometheus label string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryMessage) Reset() {
	*x = TelemetryMessage{}
	mi := &file_mq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryMessage) ProtoMessage() {}

func (x *TelemetryMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryMessage.ProtoReflect.Descriptor instead.
func (*TelemetryMessage) Descriptor() ([]byte, []int) {
	return file_mq_proto_rawDescGZIP(), []int{0}
}

func (x *TelemetryMessage) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *TelemetryMessage) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *TelemetryMessage) GetGpuId() string {
	if x != nil {
		return x.GpuId
	}
	return ""
}

func (x *TelemetryMessage) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *TelemetryMessage) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *TelemetryMessage) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *TelemetryMessage) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *TelemetryMessage) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *TelemetryMessage) GetPod() string {
	if x != nil {
		return x.Pod
	}
	return ""
}

func (x *TelemetryMessage) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *TelemetryMessage) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *TelemetryMessage) GetLabelsRaw() string {
	if x != nil {
		return x.LabelsRaw
	}
	return ""
}

type ProduceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *TelemetryMessage      `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProduceRequest) Reset() {
	*x = ProduceRequest{}
	mi := &file_mq_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProduceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceRequest) ProtoMessage() {}

func (x *ProduceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mq_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceRequest.ProtoReflect.Descriptor instead.
func (*ProduceRequest) Descriptor() ([]byte, []int) {
	return file_mq_proto_rawDescGZIP(), []int{1}
}

func (x *ProduceRequest) GetMessage() *TelemetryMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type ProduceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"` // true = enqueued (or drop-oldest fired); false only on validation error
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProduceResponse) Reset() {
	*x = ProduceResponse{}
	mi := &file_mq_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProduceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceResponse) ProtoMessage() {}

func (x *ProduceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mq_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceResponse.ProtoReflect.Descriptor instead.
func (*ProduceResponse) Descriptor() ([]byte, []int) {
	return file_mq_proto_rawDescGZIP(), []int{2}
}

func (x *ProduceResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

// ConsumeRequest is intentionally minimal. consumer_id is optional; used only
// for server-side logging to correlate which Collector instance holds a stream.
type ConsumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerId    string                 `protobuf:"bytes,1,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeRequest) Reset() {
	*x = ConsumeRequest{}
	mi := &file_mq_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeRequest) ProtoMessage() {}

func (x *ConsumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mq_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeRequest.ProtoReflect.Descriptor instead.
func (*ConsumeRequest) Descriptor() ([]byte, []int) {
	return file_mq_proto_rawDescGZIP(), []int{3}
}

func (x *ConsumeRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

var File_mq_proto protoreflect.FileDescriptor

const file_mq_proto_rawDesc = "" +
	"\n" +
	"\bmq.proto\x12\x05mq.v1\"\xd2\x02\n" +
	"\x10TelemetryMessage\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x1f\n" +
	"\vmetric_name\x18\x02 \x01(\tR\n" +
	"metricName\x12\x15\n" +
	"\x06gpu_id\x18\x03 \x01(\tR\x05gpuId\x12\x16\n" +
	"\x06device\x18\x04 \x01(\tR\x06device\x12\x12\n" +
	"\x04uuid\x18\x05 \x01(\tR\x04uuid\x12\x1d\n" +
	"\n" +
	"model_name\x18\x06 \x01(\tR\tmodelName\x12\x1a\n" +
	"\bhostname\x18\a \x01(\tR\bhostname\x12\x1c\n" +
	"\tcontainer\x18\b \x01(\tR\tcontainer\x12\x10\n" +
	"\x03pod\x18\t \x01(\tR\x03pod\x12\x1c\n" +
	"\tnamespace\x18\n" +
	" \x01(\tR\tnamespace\x12\x14\n" +
	"\x05value\x18\v \x01(\x01R\x05value\x12\x1d\n" +
	"\n" +
	"labels_raw\x18\f \x01(\tR\tlabelsRaw\"C\n" +
	"\x0eProduceRequest\x121\n" +
	"\amessage\x18\x01 \x01(\v2\x17.mq.v1.TelemetryMessageR\amessage\"-\n" +
	"\x0fProduceResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"1\n" +
	"\x0eConsumeRequest\x12\x1f\n" +
	"\vconsumer_id\x18\x01 \x01(\tR\n" +
	"consumerId2\x82\x01\n" +
	"\tMQService\x128\n" +
	"\aProduce\x12\x15.mq.v1.ProduceRequest\x1a\x16.mq.v1.ProduceResponse\x12;\n" +
	"\aConsume\x12\x15.mq.v1.ConsumeRequest\x1a\x17.mq.v1.TelemetryMessage0\x01B!Z\x1fgithub.com/ajitg/vantage/pkg/pbb\x06proto3"

var (
	file_mq_proto_rawDescOnce sync.Once
	file_mq_proto_rawDescData []byte
)

func file_mq_proto_rawDescGZIP() []byte {
	file_mq_proto_rawDescOnce.Do(func() {
		file_mq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mq_proto_rawDesc), len(file_mq_proto_rawDesc)))
	})
	return file_mq_proto_rawDescData
}

var file_mq_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_mq_proto_goTypes = []any{
	(*TelemetryMessage)(nil), // 0: mq.v1.TelemetryMessage
	(*ProduceRequest)(nil),   // 1: mq.v1.ProduceRequest
	(*ProduceResponse)(nil),  // 2: mq.v1.ProduceResponse
	(*ConsumeRequest)(nil),   // 3: mq.v1.ConsumeRequest
}
var file_mq_proto_depIdxs = []int32{
	0, // 0: mq.v1.ProduceRequest.message:type_name -> mq.v1.TelemetryMessage
	1, // 1: mq.v1.MQService.Produce:input_type -> mq.v1.ProduceRequest
	3, // 2: mq.v1.MQService.Consume:input_type -> mq.v1.ConsumeRequest
	2, // 3: mq.v1.MQService.Produce:output_type -> mq.v1.ProduceResponse
	0, // 4: mq.v1.MQService.Consume:output_type -> mq.v1.TelemetryMessage
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mq_proto_init() }
func file_mq_proto_init() {
	if File_mq_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mq_proto_rawDesc), len(file_mq_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mq_proto_goTypes,
		DependencyIndexes: file_mq_proto_depIdxs,
		MessageInfos:      file_mq_proto_msgTypes,
	}.Build()
	File_mq_proto = out.File
	file_mq_proto_goTypes = nil
	file_mq_proto_depIdxs = nil
}
