// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: mq.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MQService_Produce_FullMethodName = "/mq.v1.MQService/Produce"
	MQService_Consume_FullMethodName = "/mq.v1.MQService/Consume"
)

// MQServiceClient is the client API for MQService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MQServiceClient interface {
	// Produce enqueues a single telemetry message.
	// Never blocks. Drop-oldest fires silently when the buffer is full.
	Produce(ctx context.Context, in *ProduceRequest, opts ...grpc.CallOption) (*ProduceResponse, error)
	// Consume is a bidirectional stream implementing broker-side at-least-once delivery
	// (D-03, ADR-001). Server→client streams TelemetryMessage with broker-assigned id;
	// client→server streams ConsumeClientMsg carrying initial credit then per-message acks.
	//
	// Protocol:
	//  1. Client opens the stream and immediately sends one ConsumeClientMsg with Credit > 0.
	//  2. Server sends up to Credit messages without waiting for acks (sliding window).
	//  3. For each received message, client sends ConsumeClientMsg{AckId: msg.Id}.
	//  4. Each ack replenishes one credit slot; broker sends the next available message.
	//  5. On client disconnect, broker re-enqueues all unacked messages at the front of the
	//     ring (best-effort ordering; duplicates are absorbed downstream by DB-04/COLL-05).
	Consume(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConsumeClientMsg, TelemetryMessage], error)
}

type mQServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMQServiceClient(cc grpc.ClientConnInterface) MQServiceClient {
	return &mQServiceClient{cc}
}

func (c *mQServiceClient) Produce(ctx context.Context, in *ProduceRequest, opts ...grpc.CallOption) (*ProduceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProduceResponse)
	err := c.cc.Invoke(ctx, MQService_Produce_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mQServiceClient) Consume(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConsumeClientMsg, TelemetryMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MQService_ServiceDesc.Streams[0], MQService_Consume_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConsumeClientMsg, TelemetryMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MQService_ConsumeClient = grpc.BidiStreamingClient[ConsumeClientMsg, TelemetryMessage]

// MQServiceServer is the server API for MQService service.
// All implementations must embed UnimplementedMQServiceServer
// for forward compatibility.
type MQServiceServer interface {
	// Produce enqueues a single telemetry message.
	// Never blocks. Drop-oldest fires silently when the buffer is full.
	Produce(context.Context, *ProduceRequest) (*ProduceResponse, error)
	// Consume is a bidirectional stream implementing broker-side at-least-once delivery
	// (D-03, ADR-001). Server→client streams TelemetryMessage with broker-assigned id;
	// client→server streams ConsumeClientMsg carrying initial credit then per-message acks.
	//
	// Protocol:
	//  1. Client opens the stream and immediately sends one ConsumeClientMsg with Credit > 0.
	//  2. Server sends up to Credit messages without waiting for acks (sliding window).
	//  3. For each received message, client sends ConsumeClientMsg{AckId: msg.Id}.
	//  4. Each ack replenishes one credit slot; broker sends the next available message.
	//  5. On client disconnect, broker re-enqueues all unacked messages at the front of the
	//     ring (best-effort ordering; duplicates are absorbed downstream by DB-04/COLL-05).
	Consume(grpc.BidiStreamingServer[ConsumeClientMsg, TelemetryMessage]) error
	mustEmbedUnimplementedMQServiceServer()
}

// UnimplementedMQServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMQServiceServer struct{}

func (UnimplementedMQServiceServer) Produce(context.Context, *ProduceRequest) (*ProduceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Produce not implemented")
}
func (UnimplementedMQServiceServer) Consume(grpc.BidiStreamingServer[ConsumeClientMsg, TelemetryMessage]) error {
	return status.Error(codes.Unimplemented, "method Consume not implemented")
}
func (UnimplementedMQServiceServer) mustEmbedUnimplementedMQServiceServer() {}
func (UnimplementedMQServiceServer) testEmbeddedByValue()                   {}

// UnsafeMQServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MQServiceServer will
// result in compilation errors.
type UnsafeMQServiceServer interface {
	mustEmbedUnimplementedMQServiceServer()
}

func RegisterMQServiceServer(s grpc.ServiceRegistrar, srv MQServiceServer) {
	// If the following call panics, it indicates UnimplementedMQServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MQService_ServiceDesc, srv)
}

func _MQService_Produce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProduceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MQServiceServer).Produce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MQService_Produce_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MQServiceServer).Produce(ctx, req.(*ProduceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MQService_Consume_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MQServiceServer).Consume(&grpc.GenericServerStream[ConsumeClientMsg, TelemetryMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MQService_ConsumeServer = grpc.BidiStreamingServer[ConsumeClientMsg, TelemetryMessage]

// MQService_ServiceDesc is the grpc.ServiceDesc for MQService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MQService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mq.v1.MQService",
	HandlerType: (*MQServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Produce",
			Handler:    _MQService_Produce_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Consume",
			Handler:       _MQService_Consume_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "mq.proto",
}
